name: .NET

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/NUnit3x.sln
    - name: Build
      run: dotnet build src/NUnit3x.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test src/NUnit3x.sln --no-build --configuration Release --verbosity normal
    
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Display Version
        run: |
          echo "SemVer: $GITVERSION_SEMVER"
      - name: Nuget Pack
        run: dotnet pack src/NUnit3x.sln --include-symbols --no-build --configuration Release /p:Version=${GITVERSION_SEMVER} --output
      
