name: .NET

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/NUnit3x.sln
    - name: Build
      run: dotnet build src/NUnit3x.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test src/NUnit3x.sln --no-build --configuration Release --verbosity normal
    
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Use GitVersion
        uses: gittools/actions/gitversion/execute@v0.9.7
        id: gitversion
      - name: Display Version
        run: |
          echo "SemVer: ${{steps.gitversion.outputs.semVer}}"
      - name: Nuget Pack
        run: dotnet pack src/NUnit3x.sln --include-symbols --configuration Release /p:Version=${{steps.gitversion.outputs.semVer}} --output ./
      - name: Nuget Push
        run: dotnet nuget push ./NUnit3x.${{steps.gitversion.outputs.semVer}}.nupkg --api-key ${NUGET_ORG_TOKEN} --source nuget
      - name: Nuget Push Symbols
        run: dotnet nuget push ./NUnit3x.${{steps.gitversion.outputs.semVer}}.symbols.nupkg --api-key ${NUGET_ORG_TOKEN} --source nuget
        
      
